# Generated by Django 5.0b1 on 2023-11-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("link", models.CharField(max_length=50)),
                ("score", models.FloatField(null=True)),
                ("descr", models.CharField(max_length=50, null=True)),
                ("directer", models.CharField(max_length=255, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
